#!/bin/bash
#
# Solaris Log Management Script
# Author: System Administrator
# Description: Interactive shell program for managing and viewing system logs
# Compatible with: Oracle Solaris
#
# This script provides functionality to:
# - Display information about system logs
# - Show last 15 lines from system log files
# - Filter log entries by specific keywords
#

# Function to clear screen
clear_screen() {
    clear
}

# Function to display log information
show_log_info() {
    clear_screen
    echo "=============================================="
    echo "          SYSTEM LOGS INFORMATION"
    echo "=============================================="
    echo
    echo "WHAT ARE LOGS?"
    echo "--------------"
    echo "System logs are files that record events, activities, and messages"
    echo "generated by the operating system, applications, and system services."
    echo "They provide crucial information for:"
    echo "- System monitoring and troubleshooting"
    echo "- Security auditing"
    echo "- Performance analysis"
    echo "- Error detection and diagnosis"
    echo
    
    echo "TYPES OF LOGS IN SOLARIS:"
    echo "-------------------------"
    echo "1. System Messages: /var/adm/messages (general system activity)"
    echo "2. Authentication: /var/log/authlog (login attempts, su commands)"
    echo "3. Mail Logs: /var/log/syslog (mail system messages)"
    echo "4. Cron Jobs: /var/cron/log (scheduled task execution)"
    echo "5. Boot Messages: /var/adm/messages (system startup messages)"
    echo "6. Audit Logs: /var/audit/* (security auditing)"
    echo "7. Application Logs: Various locations depending on application"
    echo
    
    echo "WHAT IS SYSLOG?"
    echo "---------------"
    echo "Syslog is a standard protocol and logging mechanism used in Unix-like"
    echo "operating systems for message logging. It was originally developed by"
    echo "Eric Allman and is now defined by RFC 3164 and RFC 5424."
    echo
    echo "Key features of syslog:"
    echo "- Centralized logging system"
    echo "- Network-capable (can send logs over network)"
    echo "- Facility and severity level classification"
    echo "- Standard message format"
    echo
    
    echo "SYSLOG STANDARD IN SOLARIS:"
    echo "---------------------------"
    echo "Yes, Solaris follows the syslog standard. The syslogd daemon manages"
    echo "system logging and uses the standard syslog facilities and priorities:"
    echo
    echo "Facilities: kern, user, mail, daemon, auth, syslog, lpr, news, uucp, cron, local0-7"
    echo "Priorities: emerg, alert, crit, err, warning, notice, info, debug"
    echo
    echo "Configuration file: /etc/syslog.conf"
    echo "Main log file: /var/adm/messages"
    echo
    echo "Press Enter to continue..."
    read
}

# Function to show last 15 lines from system log files
show_last_lines() {
    clear_screen
    echo "=============================================="
    echo "    LAST 15 LINES FROM SYSTEM LOG FILES"
    echo "=============================================="
    echo
    
    # Array of common Solaris log files
    log_files=("/var/adm/messages" "/var/log/authlog" "/var/log/syslog")
    
    for log_file in "${log_files[@]}"; do
        echo "--- LOG FILE: $log_file ---"
        if [ -f "$log_file" ]; then
            if [ -r "$log_file" ]; then
                echo "Last 15 lines:"
                tail -15 "$log_file" 2>/dev/null || echo "Error reading file"
            else
                echo "File exists but is not readable. Check permissions."
            fi
        else
            echo "File does not exist or is not accessible."
        fi
        echo
        echo "================================================"
        echo
    done
    
    echo "Press Enter to continue..."
    read
}

# Function to search for specific word in log files
search_in_logs() {
    clear_screen
    echo "=============================================="
    echo "        SEARCH IN SYSTEM LOG FILES"
    echo "=============================================="
    echo
    
    echo "Enter the word/pattern to search for:"
    read -p "> " search_term
    
    if [ -z "$search_term" ]; then
        echo "No search term provided. Returning to menu..."
        sleep 2
        return
    fi
    
    clear_screen
    echo "=============================================="
    echo "  SEARCH RESULTS FOR: '$search_term'"
    echo "=============================================="
    echo
    
    # Array of common Solaris log files
    log_files=("/var/adm/messages" "/var/log/authlog" "/var/log/syslog")
    found_results=false
    
    for log_file in "${log_files[@]}"; do
        echo "--- SEARCHING IN: $log_file ---"
        if [ -f "$log_file" ] && [ -r "$log_file" ]; then
            # Get last 15 lines and search for the term
            results=$(tail -15 "$log_file" 2>/dev/null | grep -i "$search_term")
            if [ -n "$results" ]; then
                echo "Found matches:"
                echo "$results"
                found_results=true
            else
                echo "No matches found in the last 15 lines."
            fi
        else
            echo "File does not exist or is not readable."
        fi
        echo
        echo "================================================"
        echo
    done
    
    if [ "$found_results" = false ]; then
        echo "No results found for '$search_term' in any log files."
    fi
    
    echo
    echo "Press Enter to continue..."
    read
}

# Function to display menu
show_menu() {
    clear_screen
    echo "=============================================="
    echo "        SOLARIS LOG MANAGEMENT SYSTEM"
    echo "=============================================="
    echo
    echo "Select an option:"
    echo
    echo "1. Show Log Information (What are logs, types, syslog standard)"
    echo "2. Display last 15 lines from system log files"
    echo "3. Search for specific word in log files"
    echo "4. Exit"
    echo
    echo "=============================================="
    echo -n "Enter your choice [1-4]: "
}

# Function to check if running as root (recommended for log access)
check_privileges() {
    if [ "$(id -u)" -ne 0 ]; then
        echo "WARNING: You are not running as root (superuser)."
        echo "Some log files may not be accessible."
        echo "For full functionality, run as: sudo $0"
        echo
        echo "Press Enter to continue anyway..."
        read
    fi
}

# Main program loop
main() {
    # Check privileges
    check_privileges
    
    while true; do
        show_menu
        read choice
        
        case $choice in
            1)
                show_log_info
                ;;
            2)
                show_last_lines
                ;;
            3)
                search_in_logs
                ;;
            4)
                clear_screen
                echo "Thank you for using Solaris Log Management System!"
                echo "Goodbye!"
                exit 0
                ;;
            *)
                echo "Invalid option. Please select 1-4."
                sleep 2
                ;;
        esac
    done
}

# Script execution starts here
echo "Starting Solaris Log Management System..."
sleep 1
main
