#!/bin/bash
# log_review_menu.sh
# A script to review system logs with a simple menu

while true; do
    clear
    echo "=============================="
    echo "     SYSTEM LOG REVIEW MENU   "
    echo "=============================="
    echo "1. What are logs?"
    echo "2. What types of logs exist in this system?"
    echo "3. What is syslog and does this system follow it?"
    echo "4. Show last 15 lines of 3 important logs"
    echo "5. Search for a word in those last 15 lines"
    echo "6. Exit"
    echo "=============================="
    read -p "Choose an option: " choice

    case $choice in
        1)
            clear
            echo "🔹 Logs are records generated by the system and applications."
            echo "   They contain information about events, errors, warnings, and activity."
            echo "   Administrators use them for monitoring, troubleshooting, and auditing."
            read -p "Press Enter to return to the menu..."
            ;;
        2)
            clear
            echo "🔹 Common log types in Linux:"
            echo "   - /var/log/syslog (general system activity)"
            echo "   - /var/log/auth.log (authentication attempts)"
            echo "   - /var/log/kern.log (kernel messages)"
            echo "   - /var/log/dmesg   (hardware & boot messages)"
            read -p "Press Enter to return to the menu..."
            ;;
        3)
            clear
            echo "🔹 Syslog is a standard protocol for log message formatting and delivery."
            echo "   It defines severity levels and facilities (system components)."
            echo "   Most Linux distributions use syslog-compatible daemons (rsyslog, syslog-ng)."
            echo "   Yes, the logs in this system follow the syslog standard."
            read -p "Press Enter to return to the menu..."
            ;;
        4)
            clear
            echo "🔹 Showing last 15 lines of 3 important logs..."
            echo "---- /var/log/syslog ----"
            tail -n 15 /var/log/syslog 2>/dev/null || echo "File not found"
            echo
            echo "---- /var/log/auth.log ----"
            tail -n 15 /var/log/auth.log 2>/dev/null || echo "File not found"
            echo
            echo "---- /var/log/kern.log ----"
            tail -n 15 /var/log/kern.log 2>/dev/null || echo "File not found"
            read -p "Press Enter to return to the menu..."
            ;;
        5)
            clear
            read -p "Enter the word to search: " word
            echo "🔹 Searching for '$word' in last 15 lines of logs..."
            echo "---- /var/log/syslog ----"
            tail -n 15 /var/log/syslog 2>/dev/null | grep --color=always -i "$word"
            echo
            echo "---- /var/log/auth.log ----"
            tail -n 15 /var/log/auth.log 2>/dev/null | grep --color=always -i "$word"
            echo
            echo "---- /var/log/kern.log ----"
            tail -n 15 /var/log/kern.log 2>/dev/null | grep --color=always -i "$word"
            read -p "Press Enter to return to the menu..."
            ;;
        6)
            echo "Exiting..."
            exit 0
            ;;
        *)
            echo "Invalid option. Try again."
            sleep 1
            ;;
    esac
done
